[greeter]
background=/usr/share/backgrounds/ozorio/ozorio-aurora.svg
theme-name=Ozorio-Aurora
icon-theme-name=Adwaita
font-name=Sans 10
xft-antialias=true
xft-dpi=96
xft-hintstyle=hintslight
xft-rgba=rgb
show-clock=true
clock-format=%H:%M
indicators=~host;~spacer;~clock;~spacer;~session;~language;~a11y;~power
position=50%,center 50%,center
user-background=false
